### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Valiec** [OtisGoodman/Turmy#6]
I get this error upon running `npm run compile` (`npm i` runs fine):

```> turmy@2.1.0 compile /Users/[USERNAME]/Desktop/Turmy
> electron-packager . Turmy --overwrite --platform=win32 --arch=ia32 --prune=true --out=build --version-string.CompanyName=OtisGoodman --version-string.FileDescription="A Discord Webhook For Trolling", --version-string.ProductName="Turmy" -- icon=ico.ico

sh: electron-packager: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! turmy@2.1.0 compile: `electron-packager . Turmy --overwrite --platform=win32 --arch=ia32 --prune=true --out=build --version-string.CompanyName=OtisGoodman --version-string.FileDescription="A Discord Webhook For Trolling", --version-string.ProductName="Turmy" -- icon=ico.ico`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the turmy@2.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[USERNAME]/.npm/_logs/2020-03-23T16_19_51_754Z-debug.log```

System details:

OS X 10.12.6
npm 6.13.4

**Comment by OtisGoodman** [comment]
`> electron-packager . Turmy --overwrite --platform=win32 --arch=ia32 --prune=true --out=build --version-string.CompanyName=OtisGoodman --version-string.FileDescription="A Discord Webhook For Trolling", --version-string.ProductName="Turmy" -- icon=ico.ico
`
This compile script is ment for windows `--platform=win32 --arch=ia32 ` mostlikely a mac compile script is needed.

**Comment by Valiec** [comment]
Thanks, but you might need to add "get a version of `electron-packager` for your OS" to the build instructions.

**Comment by OtisGoodman** [comment]
The way the app is structured does not really allow mac builds, build.js adds windows installers and stuff.  In order for mac users to run this smoothly, there would also need to be some changes to the way the app handles being minimized.

**Comment by Valiec** [comment]
OK, I'll build it on windows then.
